apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: vllm-qwen
  namespace: kserve
spec:
  predictor:
    containers:
      - name: kserve-container
        image: vllm/vllm-openai:latest
        args:
          - --model=Qwen/Qwen3-0.6B
          - --dtype=bfloat16
          - --max-model-len=8192
          - --gpu-memory-utilization=0.85
          - --max-num-seqs=256
          - --kv-cache-dtype=fp8
          - --enable-prefix-caching
        resources:
          limits:
            cpu: "3"
            nvidia.com/gpu: "1"
            memory: 12Gi
          requests:
            nvidia.com/gpu: "1"
            memory: 8Gi
            cpu: "1"
        ports:
          - containerPort: 8000
            protocol: TCP