apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: vllm-qwen
  namespace: kserve
spec:
  predictor:
    containers:
      - name: kserve-container
        image: vllm/vllm-openai:latest
        args:
          - --model=Qwen/Qwen3-0.6B
          - --dtype=bfloat16
          - --max-model-len=2048
          - --gpu-memory-utilization=0.5
          - --enable-lora
          - --enable-prefix-caching
          - --block-size=32
          - --cpu-offload-gb=2
          - --swap-space=8
        resources:
          limits:
            cpu: "4"
            nvidia.com/gpu: "1"
            memory: 10Gi
          requests:
            nvidia.com/gpu: "1"
            memory: 8Gi
            cpu: "2"
        ports:
          - containerPort: 8000
            protocol: TCP